services:
  img-service-nest:
    container_name: img-service-nest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Almaty
    restart: always
    ports:
      - "9980:3000"
    volumes:
      - ./uploads:/app/uploads
